# Generated by Django 4.0.2 on 2022-02-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1028)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(default='brigittesprung@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1028)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='brigittesprung@gmail.com', max_length=254)),
                ('type', models.CharField(max_length=1028)),
                ('submitted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.client')),
                ('relationshipManager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.relationshipmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1028)),
                ('file', models.FileField(upload_to='tmp/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('documentRequest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.documentrequest')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='relationshipManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.relationshipmanager'),
        ),
    ]
