# Generated by Django 4.0.2 on 2022-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipmanager',
            name='email',
            field=models.EmailField(default='brigittesprung@gmail.com', max_length=254),
        ),
    ]
