# Generated by Django 4.0.2 on 2022-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='brigittesprung@gmail.com', max_length=254),
        ),
    ]
